// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// ITabStrip
// properties
#define DISPID_TABSTRIPCTL_ACTIVETAB											DISPID_VALUE
#define DISPID_TABSTRIPCTL_ALLOWDRAGDROP									1
#define DISPID_TABSTRIPCTL_APPEARANCE											2
#define DISPID_TABSTRIPCTL_BORDERSTYLE										3
#define DISPID_TABSTRIPCTL_CARETTAB												4
#define DISPID_TABSTRIPCTL_CLOSEABLETABS									5
#define DISPID_TABSTRIPCTL_DISABLEDEVENTS									6
#define DISPID_TABSTRIPCTL_DISPLAYAREAHEIGHT							7
#define DISPID_TABSTRIPCTL_DISPLAYAREALEFT								8
#define DISPID_TABSTRIPCTL_DISPLAYAREATOP									9
#define DISPID_TABSTRIPCTL_DISPLAYAREAWIDTH								10
//#define DISPID_TABSTRIPCTL_DONTREDRAW											11
#define DISPID_TABSTRIPCTL_DRAGACTIVATETIME								12
#define DISPID_TABSTRIPCTL_DRAGGEDTABS										13
#define DISPID_TABSTRIPCTL_DRAGSCROLLTIMEBASE							14
#define DISPID_TABSTRIPCTL_DROPHILITEDTAB									15
#define DISPID_TABSTRIPCTL_ENABLED												DISPID_ENABLED
#define DISPID_TABSTRIPCTL_FIXEDTABWIDTH									16
#define DISPID_TABSTRIPCTL_FOCUSONBUTTONDOWN							17
#define DISPID_TABSTRIPCTL_FONT														18
#define DISPID_TABSTRIPCTL_HDRAGIMAGELIST									19
#define DISPID_TABSTRIPCTL_HIMAGELIST											20
#define DISPID_TABSTRIPCTL_HORIZONTALPADDING							21
#define DISPID_TABSTRIPCTL_HOTTRACKING										22
#define DISPID_TABSTRIPCTL_HOVERTIME											23
#define DISPID_TABSTRIPCTL_HWND														24
#define DISPID_TABSTRIPCTL_HWNDARROWBUTTONS								25
#define DISPID_TABSTRIPCTL_HWNDTOOLTIP										26
#define DISPID_TABSTRIPCTL_INSERTMARKCOLOR								27
#define DISPID_TABSTRIPCTL_MINTABWIDTH										28
#define DISPID_TABSTRIPCTL_MOUSEICON											29
#define DISPID_TABSTRIPCTL_MOUSEPOINTER										30
#define DISPID_TABSTRIPCTL_MULTIROW												31
#define DISPID_TABSTRIPCTL_MULTISELECT										32
#define DISPID_TABSTRIPCTL_OWNERDRAWN											33
#define DISPID_TABSTRIPCTL_PROCESSCONTEXTMENUKEYS					34
#define DISPID_TABSTRIPCTL_RAGGEDTABROWS									35
#define DISPID_TABSTRIPCTL_REGISTERFOROLEDRAGDROP					36
#define DISPID_TABSTRIPCTL_RIGHTTOLEFT										37
#define DISPID_TABSTRIPCTL_SCROLLTOOPPOSITE								38
#define DISPID_TABSTRIPCTL_SHOWBUTTONSEPARATORS						39
#define DISPID_TABSTRIPCTL_SHOWDRAGIMAGE									40
#define DISPID_TABSTRIPCTL_SHOWTOOLTIPS										41
#define DISPID_TABSTRIPCTL_STYLE													42
#define DISPID_TABSTRIPCTL_SUPPORTOLEDRAGIMAGES						43
#define DISPID_TABSTRIPCTL_TABBOUNDINGBOXDEFINITION				44
#define DISPID_TABSTRIPCTL_TABCAPTIONALIGNMENT						45
#define DISPID_TABSTRIPCTL_TABHEIGHT											46
#define DISPID_TABSTRIPCTL_TABPLACEMENT										47
#define DISPID_TABSTRIPCTL_TABS														48
#define DISPID_TABSTRIPCTL_USEFIXEDTABWIDTH								49
#define DISPID_TABSTRIPCTL_USESYSTEMFONT									50
#define DISPID_TABSTRIPCTL_VERSION												51
#define DISPID_TABSTRIPCTL_VERTICALPADDING								52
#define DISPID_TABSTRIPCTL_HHIGHRESIMAGELIST							66
#define DISPID_TABSTRIPCTL_OLEDRAGIMAGESTYLE							67
//#define DISPID_TABSTRIPCTL_REFLECTCONTEXTMENUMESSAGES			68
#define DISPID_TABSTRIPCTL_CLOSEABLETABSMODE							69
// fingerprint
#define DISPID_TABSTRIPCTL_APPID													500
#define DISPID_TABSTRIPCTL_APPNAME												501
#define DISPID_TABSTRIPCTL_APPSHORTNAME										502
#define DISPID_TABSTRIPCTL_BUILD													503
#define DISPID_TABSTRIPCTL_CHARSET												504
#define DISPID_TABSTRIPCTL_ISRELEASE											505
#define DISPID_TABSTRIPCTL_PROGRAMMER											506
#define DISPID_TABSTRIPCTL_TESTER													507
// methods
#define DISPID_TABSTRIPCTL_ABOUT													DISPID_ABOUTBOX
#define DISPID_TABSTRIPCTL_BEGINDRAG											53
#define DISPID_TABSTRIPCTL_CALCULATEDISPLAYAREA						54
#define DISPID_TABSTRIPCTL_CALCULATEWINDOWRECTANGLE				55
#define DISPID_TABSTRIPCTL_COUNTTABROWS										56
#define DISPID_TABSTRIPCTL_CREATETABCONTAINER							57
#define DISPID_TABSTRIPCTL_ENDDRAG												58
#define DISPID_TABSTRIPCTL_GETCLOSESTINSERTMARKPOSITION		59
#define DISPID_TABSTRIPCTL_GETINSERTMARKPOSITION					60
#define DISPID_TABSTRIPCTL_HITTEST												61
#define DISPID_TABSTRIPCTL_LOADSETTINGSFROMFILE						62
#define DISPID_TABSTRIPCTL_OLEDRAG												63
#define DISPID_TABSTRIPCTL_REFRESH												DISPID_REFRESH
#define DISPID_TABSTRIPCTL_SAVESETTINGSTOFILE							64
#define DISPID_TABSTRIPCTL_SETINSERTMARKPOSITION					65
#define DISPID_TABSTRIPCTL_FINISHOLEDRAGDROP							70


// _ITabStripEvents
// methods
#define DISPID_TABSTRIPCTLE_ABORTEDDRAG										1
#define DISPID_TABSTRIPCTLE_ACTIVETABCHANGED							DISPID_VALUE
#define DISPID_TABSTRIPCTLE_ACTIVETABCHANGING							2
#define DISPID_TABSTRIPCTLE_CARETCHANGED									3
#define DISPID_TABSTRIPCTLE_CLICK													4
#define DISPID_TABSTRIPCTLE_CONTEXTMENU										5
#define DISPID_TABSTRIPCTLE_DBLCLICK											6
#define DISPID_TABSTRIPCTLE_DESTROYEDCONTROLWINDOW				7
#define DISPID_TABSTRIPCTLE_DRAGMOUSEMOVE									8
#define DISPID_TABSTRIPCTLE_DROP													9
#define DISPID_TABSTRIPCTLE_FREETABDATA										10
#define DISPID_TABSTRIPCTLE_INSERTEDTAB										11
#define DISPID_TABSTRIPCTLE_INSERTINGTAB									12
#define DISPID_TABSTRIPCTLE_KEYDOWN												13
#define DISPID_TABSTRIPCTLE_KEYPRESS											14
#define DISPID_TABSTRIPCTLE_KEYUP													15
#define DISPID_TABSTRIPCTLE_MCLICK												16
#define DISPID_TABSTRIPCTLE_MDBLCLICK											17
#define DISPID_TABSTRIPCTLE_MOUSEDOWN											18
#define DISPID_TABSTRIPCTLE_MOUSEENTER										19
#define DISPID_TABSTRIPCTLE_MOUSEHOVER										20
#define DISPID_TABSTRIPCTLE_MOUSELEAVE										21
#define DISPID_TABSTRIPCTLE_MOUSEMOVE											22
#define DISPID_TABSTRIPCTLE_MOUSEUP												23
#define DISPID_TABSTRIPCTLE_OLECOMPLETEDRAG								24
#define DISPID_TABSTRIPCTLE_OLEDRAGDROP										25
#define DISPID_TABSTRIPCTLE_OLEDRAGENTER									26
#define DISPID_TABSTRIPCTLE_OLEDRAGLEAVE									27
#define DISPID_TABSTRIPCTLE_OLEDRAGMOUSEMOVE							28
#define DISPID_TABSTRIPCTLE_OLEGIVEFEEDBACK								29
#define DISPID_TABSTRIPCTLE_OLEQUERYCONTINUEDRAG					30
#define DISPID_TABSTRIPCTLE_OLESETDATA										31
#define DISPID_TABSTRIPCTLE_OLESTARTDRAG									32
#define DISPID_TABSTRIPCTLE_OWNERDRAWTAB									33
#define DISPID_TABSTRIPCTLE_RCLICK												34
#define DISPID_TABSTRIPCTLE_RDBLCLICK											35
#define DISPID_TABSTRIPCTLE_RECREATEDCONTROLWINDOW				36
#define DISPID_TABSTRIPCTLE_REMOVEDTAB										37
#define DISPID_TABSTRIPCTLE_REMOVINGTAB										38
#define DISPID_TABSTRIPCTLE_RESIZEDCONTROLWINDOW					39
#define DISPID_TABSTRIPCTLE_TABBEGINDRAG									40
#define DISPID_TABSTRIPCTLE_TABBEGINRDRAG									41
#define DISPID_TABSTRIPCTLE_TABGETINFOTIPTEXT							42
#define DISPID_TABSTRIPCTLE_TABMOUSEENTER									43
#define DISPID_TABSTRIPCTLE_TABMOUSELEAVE									44
#define DISPID_TABSTRIPCTLE_TABSELECTIONCHANGED						45
#define DISPID_TABSTRIPCTLE_OLEDRAGENTERPOTENTIALTARGET		46
#define DISPID_TABSTRIPCTLE_OLEDRAGLEAVEPOTENTIALTARGET		47
#define DISPID_TABSTRIPCTLE_OLERECEIVEDNEWDATA						48
#define DISPID_TABSTRIPCTLE_XCLICK												49
#define DISPID_TABSTRIPCTLE_XDBLCLICK											50


// ITabStripTab
// properties
#define DISPID_TST_ACTIVE																	1
#define DISPID_TST_CARET																	2
#define DISPID_TST_DROPHILITED														3
#define DISPID_TST_HEIGHT																	4
#define DISPID_TST_ICONINDEX															5
#define DISPID_TST_ID																			6
#define DISPID_TST_INDEX																	7
#define DISPID_TST_LEFT																		8
#define DISPID_TST_SELECTED																9
#define DISPID_TST_TABDATA																10
#define DISPID_TST_TEXT																		DISPID_VALUE
#define DISPID_TST_TOP																		11
#define DISPID_TST_WIDTH																	12
#define DISPID_TST_HASSOCIATEDWINDOW											14
#define DISPID_TST_HASCLOSEBUTTON													15
// methods
#define DISPID_TST_CREATEDRAGIMAGE												13


// ITabStripTabs
// properties
#define DISPID_TSTS_CASESENSITIVEFILTERS									1
#define DISPID_TSTS_COMPARISONFUNCTION										2
#define DISPID_TSTS_FILTER																3
#define DISPID_TSTS_FILTERTYPE														4
#define DISPID_TSTS_ITEM																	DISPID_VALUE
#define DISPID_TSTS__NEWENUM															DISPID_NEWENUM
// methods
#define DISPID_TSTS_ADD																		5
#define DISPID_TSTS_CONTAINS															6
#define DISPID_TSTS_COUNT																	7
#define DISPID_TSTS_DESELECTALL														8
#define DISPID_TSTS_REMOVE																9
#define DISPID_TSTS_REMOVEALL															10


// ITabStripTabContainer
// properties
#define DISPID_TSTC_ITEM																	DISPID_VALUE
#define DISPID_TSTC__NEWENUM															DISPID_NEWENUM
// methods
#define DISPID_TSTC_ADD																		1
#define DISPID_TSTC_CLONE																	2
#define DISPID_TSTC_COUNT																	3
#define DISPID_TSTC_CREATEDRAGIMAGE												4
#define DISPID_TSTC_REMOVE																5
#define DISPID_TSTC_REMOVEALL															6


// IVirtualTabStripTab
// properties
#define DISPID_VTST_DROPHILITED														1
#define DISPID_VTST_ICONINDEX															2
#define DISPID_VTST_INDEX																	3
#define DISPID_VTST_SELECTED															4
#define DISPID_VTST_TABDATA																5
#define DISPID_VTST_TEXT																	DISPID_VALUE
// methods


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR																	1
#define DISPID_ODO_GETCANONICALFORMAT											2
#define DISPID_ODO_GETDATA																3
#define DISPID_ODO_GETFORMAT															4
#define DISPID_ODO_SETDATA																5
#define DISPID_ODO_GETDROPDESCRIPTION											6
#define DISPID_ODO_SETDROPDESCRIPTION											7
